### PR TITLE
adjust dependency version range for org.eventb.core

### PR DESCRIPTION
**Pull request by cfsnook**

### CODE REVIEW

**Comment by cfsnook** [comment]
Note: intend to replace the dummy refactoring with the real one before next release of this feature.
We might also remove the generator but this would mean changing all the diagrams to use the generic translator instead.

**Comment by cfsnook** [comment]
@Dana: I have fixed the bug in the enumeration translation as commanded

**Comment by dd4g12** [comment]
I just tried it, it still freezes when running enumeration

**Comment by cfsnook** [comment]
Works for me... please could you check you have f78441b
failing that.. could you send me the model that fails.

**Comment by dd4g12** [comment]
Sorry my fault I didn't have 78441b, tested again and no problems. Thanks

**Comment by cfsnook** [comment]
Please note that I have just some updates to things in the feature.properties and sdk

**Review by tshoang — APPROVED** [review]

**Pull request merged**
